version: "3.4"
services:
  db:
    container_name: student-db
    image: mysql:8.0.32
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'studentdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'student-admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'abdelghani2023@mysql'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'abdelghani2023@mysql'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /Volumes/Entertainer/te/docker-data-student-db:/var/lib/mysql

